name: push_to_prod
on:
  workflow_run:
    workflows: ["pull_request"]   # Must match the name of your PR workflow
    types:
      - completed
      
jobs:
  job_id:
    name: checkout_and_deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to OCI Weather VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/oci_experiments
            git checkout main
            git pull origin main
